version: 2.1

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: 'circleci/android:api-25-alpha'
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Accept Android SDK licences
          command: sdkmanager --update && yes | sdkmanager --licenses
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew build sonarqube

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
